language: rust
cache: cargo
before_script:
  - rustup component add clippy
script:
  - cargo clippy -- -D warnings
  - cargo test
branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master