[package]
authors = ["Pavel Tupitsyn <ptupitsyn@apache.org>"]
edition = "2018"
name = "klopodavka-yew"
readme = "README.md"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "^0.2"
yew = "0.12"
klopodavka-lib = { path = "../klopodavka-lib" }